name: CI

on:
  push:
    branches:
      - main

# PermissÃµes para o id token
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build and push'
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    node: [ 18, 20, 22 ]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup node | ${{ matrix.node }}
      uses: actions/setup-node@v6
      with:
        node_version: 24
    #    node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run test

    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: arn:aws:iam::972775291333:role/ecr-role
        aws-region: us-east-2
    
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      

    - name: Build docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ steps.generate_tag.outputs.sha }}
      run: | 
        docker build -t $REGISTRY/rocketseat-ci:$TAG .
        docker push $REGISTRY/rocketseat-ci:$TAG
  


    #- name: Login into the container registry
    #  uses: docker/login-action@v3
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    #- name: Build and Push
    #  uses: docker/build-push-action@v5
    #  with:
    #    push: true
    #    tags: kauaqt/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }},kauaqt/rocketseat-ci-api:latest

#    - name: Build docker image
#      run: docker build -t kauaqt/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .

#    - name: Push image
#      run: docker push kauaqt/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}